# roles/common/tasks/debian.yml
- name: Ensure git is present
  apt:
    name: git
    state: present

- name: Ensure python-pip is present
  apt:
    name: python-pip
    state: present

- name: Ensure kdiff3 is present
  apt:
    name: kdiff3
    state: present

- name: Ensure vim is present
  apt:
    name: vim
    state: present

- name: Ensure vim-gtk is present
  apt:
    name: vim-gtk
    state: present

- name: Ensure mc is present
  apt:
    name: mc
    state: present

- name: Ensure virtualbox-guest-dkms is present
  apt:
    name: virtualbox-guest-dkms
    state: present

- name: Ensure virtualbox-guest-utils is present
  apt:
    name: virtualbox-guest-utils
    state: present

- name: Ensure virtualbox-guest-x11 is present
  apt:
    name: virtualbox-guest-x11
    state: present
